apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260602-155118-0brq6drcyxzx-service
spec:
  selector:
    app: enterprise-system-20260602-155118-0brq6drcyxzx
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
